databases:
  - name: wishlist-app-db
    plan: free

services:
  - type: web
    name: wishlist-app
    env: node
    plan: free
    buildCommand: yarn --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wishlist-app-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
